### ISSUE TITLE
No icon on the task bar kde neon 5.16.3

### ISSUE THREAD

**Issue by Lvaskz** [flathub/com.github.unrud.VideoDownloader#1]
Hi, I recently installed the app but when I run it the icon is missing on the task bar 
see
![ksnip_20190726-225143](https://user-images.githubusercontent.com/29207169/61990159-54be0400-aff8-11e9-8f56-53b84aae9a4f.png)
I am using kde neon 5.16.3
64 bits 
By the way the snap app the icon from appmenu and taskbar is missing

**Comment by Unrud** [comment]
Fixed: https://github.com/Unrud/video-downloader/commit/133c49594dfaaff0e1997f8fefa8794963201b46
