### ISSUE TITLE
Use mirror until the situation is resolved

### ISSUE THREAD

**Issue by Eonfge** [flathub/com.github.unrud.VideoDownloader#5]
Thanks for your efforts so far, and it's a shame to see your application go EoL. You made a simple but useful downloader, which really filled a niche.

As for using youtube-dl. Right now, other applications on Flathub currently use the Debian mirror:
https://packages.debian.org/sid/youtube-dl

Keep in mind that the legal issue has not been resolved yet. It's unclear when (and if) youtube-dl comes back, and if it will still use that name, but you should know that other applications still use YouTube DL and that almost all distributions ship it by default:
https://pkgs.org/download/youtube-dl

**Comment by edwincc-vital** [comment]
can I have the source code for myself or find the flatpak files somewhere ?

**Comment by edwincc-vital** [comment]
can I have the source code somewhere ? or the flatpak files ?

**Comment by Unrud** [comment]
> Keep in mind that the legal issue has not been resolved yet. It's unclear when (and if) youtube-dl comes back, and if it will still use that name

Yeah, I'm not interested in working on it under this circumstances.

> can I have the source code somewhere ?

https://github.com/unrud/video-downloader

**Comment by Eonfge** [comment]
I can respect that.

For advanced users interested in using the last functional version, you can use the following commands:
- `flatpak install flathub com.github.unrud.VideoDownloader`
- `flatpak remote-info --log flathub com.github.unrud.VideoDownloader`
- `sudo flatpak update --commit=e94c3b9307e7611428ed134cf2cd597bd5be5623f38bed83684e7c36d5429edf com.github.unrud.VideoDownloader`
- `sudo flatpak mask com.github.unrud.VideoDownloader`

Be aware that you will not receive any updates, even if upstream continues work, which might over time introduce incompatibilities or security issues.

**Comment by edwincc-vital** [comment]
Thanks @Eonfge , I was searching for the "mask" command actually.
I see no "flatpak download" command so I wonder if that is possible to obtain sort of a flatpak package ready to install so I could use it as backup ?

**Comment by Eonfge** [comment]
@Unrud Youtube-DL has been restored on GitHub. Thumbs up to the EFF:
https://github.com/github/dmca/blob/master/2020/11/2020-11-16-RIAA-reversal-effletter.pdf

**Comment by Unrud** [comment]
The project is back.

**Comment by Eonfge** [comment]
You might want to talk to Gustavo Peredo who forked your project:
https://github.com/GustavoPeredo/video-downloader

There are now two applications on Flathub, both called Video Downloader. 

@bilelmoussaoui Do we have any protocol for these kinds of things?

**Comment by felipehw** [comment]
@Unrud ... is there any talks with @GustavoPereto about the current situation?
