### ISSUE TITLE
on Nov 17, 2020, 12:51pm EST  GitHub reinstated a YouTube video downloader

### ISSUE THREAD

**Issue by sltgc** [flathub/com.github.unrud.VideoDownloader#6]
Hi, 
Hope you'll continue ou re-open your videodowmnloader project here and on your main
Have you heard the recent news ? 
TheVerge on Nov 17, 2020, 12:51pm EST 
[GitHub reinstated a YouTube video downloader that the RIAA claimed was a piracy tool](https://www.theverge.com/2020/11/17/21571473/github-youtube-dl-downloader-riaa-copyright-1201-takedown-reinstated)

Thanks !

**Comment by HugLifeTiZ** [comment]
It kind of seems like the project owner isn't interested in maintaining it anymore, because youtube-dl has been reinstated for some time now and yet the original repo is still archived. Maybe someone has forked it or eventually will.

**Comment by Unrud** [comment]
The project is back.
